# file: postgresql/tasks/main.yml

- include: install.yml
  tags: [postgresql, postgresql-install]

- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: users.yml
  tags: [postgresql, postgresql-users]

- include: databases.yml
  tags: [postgresql, postgresql-databases]

- include: users_privileges.yml
  tags: [postgresql, postgresql-users]
